### ISSUE TITLE
Error: Cannot find module 'jsx-ast-utils'

### ISSUE THREAD

**Issue by scagood** [SonarSource/SonarJS#4777]
JIRA ticket: [ESLINTJS-47](https://sonarsource.atlassian.net/browse/ESLINTJS-47)

When updating to v2 I got the following error:

```
ESLint: 9.9.0

Error: Cannot find module 'jsx-ast-utils'
Require stack:
- /home/runner/work/eslint/eslint/node_modules/.store/eslint-plugin-sonarjs-virtual-06d[8](https://github.com/scagood/eslint/actions/runs/10510985174/job/29120892210?pr=588#step:5:9)ccbe8f/package/lib/helpers/accessibility.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:[9](https://github.com/scagood/eslint/actions/runs/10510985174/job/29120892210?pr=588#step:5:10)86:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/eslint/eslint/node_modules/.store/eslint-plugin-sonarjs-virtual-06d8ccbe8f/package/lib/helpers/accessibility.js:26:25)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:[10](https://github.com/scagood/eslint/actions/runs/10510985174/job/29120892210?pr=588#step:5:11))
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:[12](https://github.com/scagood/eslint/actions/runs/10510985174/job/29120892210?pr=588#step:5:13)33:19)
```

https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/helpers/accessibility.ts#L21

I think this is because I am using pnpm, which blocks the implicit dependence from `eslint-plugin-react`:
```
└─  eslint-plugin-sonarjs@npm:2.0.0
   └─  eslint-plugin-react@npm:7.35.0
      └─ jsx-ast-utils@npm:3.3.5 (via npm:^2.4.1 || ^3.0.0)
```

[ESLINTJS-47]: https://sonarsource.atlassian.net/browse/ESLINTJS-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by boris-petrov** [comment]
Sorry for using your issue but I can't open a new one as it leads me to a Jira where I don't have permissions. :smile: Also, it's kind of similar. I get `Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .` with version 2 which makes sense because I don't use React in my project. So `eslint-plugin-react` should somehow be conditionally imported.

**Comment by ericmorand-sonarsource** [comment]
@scagood , thanks for the report. Can you please elaborate on this?

> I think this is because I am using pnpm, which blocks the implicit dependence from eslint-plugin-react:

**Comment by ericmorand-sonarsource** [comment]
@boris-petrov , thanks for the report. The react version is provided by the recommended configuration of the plugin. Would you mind sharing your ESLint configuration file so that we can check if something is missing?

**Comment by boris-petrov** [comment]
@ericmorand-sonarsource thanks for the support! I didn't change anything from 1.0.4 - I'm using ESLint 8 and have `sonarjs` in `plugins` and `plugin:sonarjs/recommended-legacy` in `extends` (and I've disabled a couple of rules) - that's it. It didn't give such a warning in 1.0.4.

**Comment by ericmorand-sonarsource** [comment]
@boris-petrov , thanks, I was able to reproduce the issue with ESLint 8. Give me a few minutes to investigate more and I'll create an internal ticket for you.

**Comment by ericmorand-sonarsource** [comment]
@boris-petrov , here is the internal ticket: https://sonarsource.atlassian.net/browse/ESLINTJS-46.

You should be able to track the progress from there.

**Comment by boris-petrov** [comment]
Thank you for the quick response! It would be nice if you could enable issues here as otherwise people will have a hard time reporting them.

**Comment by ericmorand-sonarsource** [comment]
Actually, you can open issues from our Community website: https://community.sonarsource.com/. This is our main (and in theory only) channel for community issues.

**Comment by scagood** [comment]
Reproduction at:
https://github.com/scagood/sonar-4777

Example error at:
https://github.com/scagood/sonar-4777/actions/runs/10523818950/job/29159312815

**Comment by ericmorand-sonarsource** [comment]
Thank you @scagood , I was able to reproduce the issue: what I was missing was that you use `yarn` and `pnpm` as the linker. And you are correct: in this context, the plugin needs to explicitly declare `jsx-ast-utils` as a dependency (actually, it should regardless of the context but the issue is only detected when using `yarn` + `pnpm`). 

I created a ticket that you can follow to track the progress on the fix: https://sonarsource.atlassian.net/browse/ESLINTJS-47

**Comment by scagood** [comment]
Merged in #4779

Thank you @ericmorand-sonarsource

**Comment by ericmorand-sonarsource** [comment]
@scagood We are publishing an alpha version to check that the issue is fixed. As soon as it is confirmed, we'll publish the the official 2.0.1 one.

**Comment by scagood** [comment]
Running on v2.0.1 here:
https://github.com/scagood/sonar-4777/actions/runs/10526050549/job/29166063611

New error is:
```
Error: Cannot find module '@typescript-eslint/utils'
Require stack:
- /home/runner/work/sonar-4777/sonar-4777/node_modules/.store/eslint-plugin-sonarjs-virtual-6d[8](https://github.com/scagood/sonar-4777/actions/runs/10526050549/job/29166063611#step:5:9)2e5d6f0/package/lib/helpers/conditions.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:133[9](https://github.com/scagood/sonar-4777/actions/runs/10526050549/job/29166063611#step:5:10):12)
    at require (node:internal/modules/helpers:125:16)
    at Object.<anonymous> (/home/runner/work/sonar-4777/sonar-4777/node_modules/.store/eslint-plugin-sonarjs-virtual-6d82e5d6f0/package/lib/helpers/conditions.js:23:17)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:[10](https://github.com/scagood/sonar-4777/actions/runs/10526050549/job/29166063611#step:5:11))
    at Module.load (node:internal/modules/cjs/loader:1317:32)
```

**Comment by scagood** [comment]
It may be worth using the [`n/no-extraneous-import`](https://github.com/eslint-community/eslint-plugin-n/blob/HEAD/docs/rules/no-extraneous-import.md) eslint rule.

**Comment by ericmorand-sonarsource** [comment]
@scagood, can you give `2.0.1-alpha.2` a try? This one should declare all the required dependencies explicitly.
@boris-petrov, can you also check that it also successfully removes the warning?

**Comment by scagood** [comment]
Commit: https://github.com/scagood/sonar-4777/commit/4fbbf3025ad96f5358ca6c32d7d040852e846f0e
Action: https://github.com/scagood/sonar-4777/actions/runs/10527948381/job/29172316153

**Comment by ericmorand-sonarsource** [comment]
@scagood , good news about the dependencies.

About the warning, in your case, it is expected: your ESLint config file does not import the recommended configuration but only the recommended rules. The React settings are part of the recommended configuration so it is normal that you get the warning.

**Comment by scagood** [comment]
Perfect, thank you again @ericmorand-sonarsource!
